[package]
name = "mailgun_v3"
description = "reqwest based web bindings for Mailgun's v3 JSON API"
readme = "README.md"
repository = "https://github.com/otterandrye/mailgun_v3"
license = "MIT"
version = "0.5.0"
authors = ["Nathan Merritt <nathan@gnmerritt.net>"]
keywords = ["mailgun", "reqwest", "email", "api"]
categories = ["api-bindings"]

[badges]
travis-ci = { repository = "otterandrye/mailgun_v3", branch = "master" }

[dependencies]
chrono = "0.4.5"
reqwest = "0.9.5"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"
